# Generated by Django 2.2.7 on 2019-12-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yes_no_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todorem',
            old_name='completes',
            new_name='complete',
        ),
    ]
